### ISSUE TITLE
CORS enable?

### ISSUE THREAD

**Issue by leossmith** [esatisfaction/esat-magento#11]
After updating to the latest version of the plugin, I get errors concerning CORS. Does the new version need CORS enabled in our apache?

**Comment by ioannis-papikas** [comment]
Hi @leossmith, thanks a lot for the issue.

Can you explain a bit more the case that you get the error so that we can reproduce and see what's happening?

**Comment by leossmith** [comment]
Hi @ioannis-papikas thank you for your reply. It seems the issue was caused by the dashboard and not the plugin. Dashboard was not updated to the latest one, leading to a 404 on the .json url, which was returning the error as a CORS error.

It was solved after a few back and forth with support. 

This is solved so it can be closed. Thanks.

**Comment by ioannis-papikas** [comment]
That's great @leossmith ! Thanks a lot for the update.
